### ISSUE TITLE
streamable input port closed due to GC

### ISSUE THREAD

**Issue by winny-** [Bogdanp/racket-http-easy#16]
Thanks for writing such an easy http library for Racket - it's keeping me productive :)

Disclaimer, I can't pretend to know how racket GC works or how executors work - this is just what I found with some testing:

Ran into an issue when using a `#:stream? #t` request - it can be closed early by `response-close!` in the case that the response struct instance is not reachable.

This code code reproduces the issue:

```racket
#lang racket

(require net/http-easy)

(define in (response-output
            (get "https://httpbin.org/image/jpeg" #:stream? #t)))

(thread-wait
 (thread
  (thunk
   (call-with-output-file "httpbin.jpg"
     (λ (out)
       (collect-garbage)                ; This causes the executor for response
                                        ; the response struct to be ran, which
                                        ; itself calls response-close! -
                                        ; removing the GC call will allow this
                                        ; code to work occasionally.
       (copy-port in out))
     #:exists 'truncate))))
```

The error message is:

```
; read-bytes-avail!: input port is closed
;   input port: #<input-port:pipe>
; Context (plain; to see better errortrace context, re-run with C-u prefix):
;   /usr/share/racket/collects/racket/private/port.rkt:113:0 copy-port
```

Tested with `Racket v8.3 [cs]`.

The code I first encountered the issue with did not use threads, just a handful of `for` iterations and procedure calls, but it's far too messy and large to share a PoC with.

The work around in my own code was to refer to place a reference to the response struct instance after any call to `copy-port`.

**Comment by Bogdanp** [comment]
Thanks for the report!  This problem is an unfortunate consequence of http-easy trying to be a little too helpful.  The port returned by `response-output` doesn't refer back to the `response` value so, because your code doesn't retain that value, the GC is free to release it eventually.  At that point, the library tries to clean up after itself, so it closes the port and releases the connection back to the pool.  As you've found, the workaround is to retain the response value intentionally.

To fix this at the library level, I can make a custom port for the outputs that retains a reference to the response to avoid this problem, so I'll give that a try this weekend.
