### ISSUE TITLE
raco pkg install http-easy also installs drracket and others

### ISSUE THREAD

**Issue by cloudrac3r** [Bogdanp/racket-http-easy#19]
Hi there! I've recently been getting into Racket and I've noticed your name a lot on many of the packages I love - thank you so much for your hard work!

Using `raco pkg install --auto --no-docs http-easy` also installs the package `drracket` and its gui dependencies, which isn't very helpful when I'm building a Racket command line program in a minimal CI environment, since it takes a long time and the CI environment doesn't have a display server.

Is there a way to install just `http-easy` without `drracket` and the other dependencies? I don't understand the package server very well, so it's likely that I missed something really obvious!

Thank you again!

**Comment by Bogdanp** [comment]
I had originally avoided splitting this code into too many packages thinking we were close to solving the issue you describe (where core documentation packages transitively depend on drracket). Since we haven't, I've gone ahead and extracted the implementation (without docs) into its own package called `http-easy-lib`. Once the package index refreshes, you should be able to install that package, and it will only bring with it the dependencies it needs.

EDIT: Looks like I registered the new package at exactly the right time and it's already available on the index.
