### ISSUE TITLE
Triming space at the end

### ISSUE THREAD

**Issue by sorawee** [Bogdanp/racket-http-easy#4]
```
(get "http://google.com ")
```

currently fails with 

```
tcp-connect: connection failed;
 host not found
  address: google.com
  port number: 80
  system error: nodename nor servname provided, or not known; gai_err=8
```

@samth suggests that a library like `racket-http-easy` probably should handle these kind of cases. See racket/racket#2663.

**Comment by Bogdanp** [comment]
We could potentially strip whitespace from the scheme and the hostname after the URL is parsed, but I don't think it's a good idea to strip that information ahead of time because it should be OK for a query string parameter to have trailing whitespace.

This snippet:

```racket
(get "http://127.1:9912/?a=hello ")
```

currently produces this request, which seems right to me:

```
GET /?a=hello+ HTTP/1.1
Host: 127.1:9912
Accept-Encoding: gzip,deflate
Content-Length: 0
user-agent: net/http-easy (macosx; racket[CS] 7.7.0.9; 0.1.0)

```

**Comment by samth** [comment]
Related to my comments on that long-ago issue, I wonder both if we can give a better error message, and what other libraries in other languages do.

**Comment by Bogdanp** [comment]
`requests` in Python seems like it doesn't to any sort of pre-processing:

```
>>> import requests
>>> requests.get("http://example.com ")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

`reqwest` in Rust looks like it strips whitespace from the hostname.

I think it's probably safe for us to have dwim behavior when somebody calls a requester with a `string`, because users can always pass in an explicit `url` value if they don't want that behavior.
