### ISSUE TITLE
Curious about project's state

### ISSUE THREAD

**Issue by evdubs** [Bogdanp/racket-http-easy#5]
Hello,

This project is currently described as a "work in progress" in the About section of the repository. I am curious to know what is left to complete to be considered "released" and if the current state is ready and stable enough.

I am currently using net/url's get-pure-port to download some HTML documents, and I seem to run into issues related to not timing out a connection. http-easy looks to have timeouts built into a request and the docs look thorough. Are there any caveats to be aware of when using http-easy?

**Comment by Bogdanp** [comment]
I think you can go ahead and use it. I don't expect to make any large API changes any time soon, in part because I'm using it in a few places and because I haven't found any glaring API mistakes so far. The last remaining big feature would be proxy support, but I don't expect that to require breaking changes to the public API. If I do make any breaking changes, they'll be documented in the "changelog" section of the docs.

BTW, if you absolutely need to avoid breakages due to package changes (both intentional and not), you might want to take a look at [racksnaps](https://racksnaps.defn.io/).

**Comment by evdubs** [comment]
Thanks for the info. I expect that my usage of http-easy will just be a single `get` call with minimal args. I imagine adding proxy support won't change that interface too much.
