### ISSUE TITLE
Passing a string variable as form data

### ISSUE THREAD

**Issue by AndrewGibb** [Bogdanp/racket-http-easy#8]
In the following snippet, I would expect `mystr` to be substituted for its contents when it is passed to the `form` keyword, but it doesn't. Is this a bug, or am I doing something wrong? Do I need some extra syntax to "expand" the string?

```racket
#lang racket/base 

(require net/http-easy)

(define mystr "a string")

(define res
  (response-json
    (post "https://httpbin.org/post"
          #:form '((a . mystr)))))

(response-close! res)
```

**Comment by Bogdanp** [comment]
In your example, the value you're passing to `#:form` is a literal association list so `mystr` is the literal symbol `mystr`, rather than the binding you defined above. You can either use quasi-quotation to construct the list and unquote to reference the binding

```racket
#lang racket/base

(require net/http-easy)

(define mystr "a string")

(response-json
 (post "https://httpbin.org/post"
       #:form `((a . ,mystr))))
```

(note the backtick ([quasiquote](https://docs.racket-lang.org/reference/quasiquote.html?q=quasiquote#%28form._%28%28lib._racket%2Fprivate%2Fletstx-scheme..rkt%29._quasiquote%29%29)) and the comma ([unquote](https://docs.racket-lang.org/reference/quasiquote.html?q=quasiquote#%28form._%28%28quote._~23~25kernel%29._unquote%29%29)))

or you can construct the list using functions

```racket
#lang racket/base

(require net/http-easy)

(define mystr "a string")

(response-json
 (post "https://httpbin.org/post"
       #:form (list
               (cons 'a mystr))))
```

**Comment by AndrewGibb** [comment]
Thanks very much for the clear answer. This has fixed my problem. Is there anywhere in the Racket documentation where this is explained? I looked around for a few hours without finding anything explaining this.

**Comment by Bogdanp** [comment]
You’re welcome. See https://docs.racket-lang.org/guide/quote.html and https://docs.racket-lang.org/guide/qq.html
